# Generated by Django 5.1.1 on 2024-09-25 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_KZ', models.CharField(max_length=255)),
                ('product_RU', models.CharField(max_length=255)),
                ('product_EN', models.CharField(max_length=255)),
                ('measure_1', models.BooleanField(default=False)),
                ('measure_2', models.BooleanField(default=False)),
                ('measure_3', models.BooleanField(default=False)),
                ('measure_4', models.BooleanField(default=False)),
                ('measure_5', models.BooleanField(default=False)),
                ('measure_6', models.BooleanField(default=False)),
                ('measure_7', models.BooleanField(default=False)),
                ('measure_8', models.BooleanField(default=False)),
                ('measure_default', models.PositiveIntegerField()),
                ('years_norm', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_KZ', models.CharField(max_length=255)),
                ('region_RU', models.CharField(max_length=255)),
                ('region_EN', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_unit_KZ', models.CharField(max_length=255)),
                ('name_unit_RU', models.CharField(max_length=255)),
                ('name_unit_EN', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('years_norm', models.FloatField()),
                ('price_for_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_for_year', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_for_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ID_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('ID_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region')),
                ('ID_measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unitofmeasurement')),
            ],
        ),
    ]
